services:
  mongodb:
    container_name: mongodb-e-commerce
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./db/mongodb:/data
    networks:
      - mongo-db-net

  mysql:
    container_name: mysql-e-commerce
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql:/var/lib/mysql
    networks:
      - mysql-db-net

  config-server:
    container_name: config-server
    image: coderabhisek/e-commerce-config-server:1.0
    networks:
      - private-net

  service-registry:
    container_name: service-registry
    image: coderabhisek/e-commerce-service-registry:1.0
    networks:
      - private-net
    ports:
      - 8761:8761
    depends_on:
      - config-server
    restart: on-failure

  authorization-server:
    container_name: authorization-server
    image: coderabhisek/e-commerce-authorization-server:1.0
    networks:
      - mongo-db-net
      - private-net
    ports:
      - 9000:9000
    depends_on:
      - mongodb
      - service-registry
    restart: on-failure

  user-service:
    container_name: user-service
    image: coderabhisek/e-commerce-user-service:1.0
    volumes:
      - ./uploads:/app/uploads
    networks:
      - mysql-db-net
      - private-net
    depends_on:
      - mysql
      - service-registry
    restart: on-failure

  product-service:
    container_name: product-service
    image: coderabhisek/e-commerce-product-service:1.0
    volumes:
      - ./uploads:/app/uploads
    networks:
      - mysql-db-net
      - private-net
    depends_on:
      - mysql
      - service-registry
    restart: on-failure

  review-service:
    container_name: review-service
    image: coderabhisek/e-commerce-review-service:1.0
    networks:
      - mysql-db-net
      - private-net
    depends_on:
      - mysql
      - service-registry
    restart: on-failure

  order-service:
    container_name: order-service
    image: coderabhisek/e-commerce-order-service:1.0
    networks:
      - mysql-db-net
      - private-net
    restart: on-failure

  payment-service:
    container_name: payment-service
    image: coderabhisek/e-commerce-payment-service:1.0
    networks:
      - mongo-db-net
      - private-net
    ports:
      - 8085:8085
    depends_on:
      - mongodb
      - service-registry
    restart: on-failure
  
  api-gateway:
    container_name: api-gateway
    image: coderabhisek/e-commerce-api-gateway:1.0
    networks:
      - private-net
    ports:
      - 8080:8080
    depends_on:
      - service-registry
    restart: on-failure

networks:
  mongo-db-net:
    driver: bridge
  mysql-db-net:
    driver: bridge
  private-net:
    driver: bridge