apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-app
  labels:
    app: mongodb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-app
  template:
    metadata:
      name: mongodb-app
      labels:
        app: mongodb-app
    spec:
      containers:
        - name: mongodb-app
          image: mongo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
              protocol: TCP
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  key: USER
                  name: mongodb-secret
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: USER_PASSWORD
                  name: mongodb-secret
          volumeMounts:
            - mountPath: /data
              name: mongodb-storage
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: e-commerce
spec:
  selector:
    app: mongodb-app
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP