eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    config:
      override-system-properties: false
services:
  urls:
    #    user: lb://user-service
    user: http://localhost:8081/users
    #    product: lb://product-service
    product: http://localhost:8082/products
    #    review: lb://product-service
    review: http://localhost:8083/reviews
    #    order: lb://order-service
    order: http://localhost:8084/orders
    cart: http://localhost:8084/carts
    #    payment: lb://payment-service
    payment: http://localhost:8085/payments