eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    config:
      override-system-properties: false
services:
  urls:
    #    user: lb://user-service
    user: http://localhost:8081/users