services:
  mongodb:
    container_name: mongodb-e-commerce
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongo:/data

  mysql:
    container_name: mysql-e-commerce
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql


volumes:
  mongo:
  mysql:
