services:
  mongodb:
    container_name: mongodb-e-commerce
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongo:/data




volumes:
  mongo:
