apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: e-commerce
  labels:
    app: mongodb-pv
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  local:
    path: "/mnt/e-commerce/db/mongodb"
  capacity:
    storage: "300Mi"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: e-commerce
spec:
  resources:
    requests:
      storage: "300Mi"
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      app: mongodb-pv
  storageClassName: standard