apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-app
  namespace: e-commerce
  labels:
    app: api-gateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-app
  template:
    metadata:
      name: api-gateway-app
      labels:
        app: api-gateway-app
    spec:
      containers:
        - name: api-gateway-app
          image: coderabhisek/e-commerce-api-gateway:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: e-commerce
spec:
  selector:
    app: api-gateway-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP

  type: LoadBalancer
